### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by DarthGandalf** [ermshiperete/Enchant#1]
I've successfully built Enchant, and written https://github.com/DarthGandalf/Enchant/commit/9db4c897e18aa7d991c1837dd2e2d9ab64f00e3b
Probably it can be somehow integrated into https://github.com/ermshiperete/Enchant/blob/FieldWorks/msvc/Build.win32.readme
But I don't know how.

**Comment by ermshiperete** [comment]
Thanks for sharing! I added your commit (slightly modified) to the FieldWorks branch.
